### ISSUE TITLE
Propostas para o FEMUG-JLLE 28/06

### ISSUE THREAD

**Issue by rafacianci** [femug-jlle/femug-jlle#4]
Vocês gostariam de falar no meetup, fazer uma **TALK** ou sugerir um **TEMA** para o FEMUG do dia 28/06? **Coloque sua proposta aqui**

## Template
Template para uma boa dica (Não é obrigatório, faça como se sentir melhor.)
```
### Titulo
Descrição da Proposta. Exemplo: Gostaria que fosse falado sobre como usar POSTCSS, como fazer um pequeno app usando essa tecnologia. É um assunto em alta e que ajudaria todos.

### Links
[Link](URL)
 
### Categoria
Talk/Tema
```

## Data 
Serão aceitas submissões e propostas **até 23/06 - Terça-Feira**

**Comment by matheuspoleza** [comment]
### JavaScript Testável
Queria fazer uma talk com um live code demonstrando como refatorar um código javascript para fazer com que ele fique mais fácil de testar. Algumas maneiras de deixar o código mais testável:
- Definir pattern
- Separar código em camadas
- Pure Functions
- Componentes
- Escolhendo a ferramenta certa

### Links
- http://alistapart.com/article/writing-testable-javascript
- https://shanetomlinson.com/2013/testing-javascript-frontend-part-1-anti-patterns-and-fixes/
- http://www.adequatelygood.com/Writing-Testable-JavaScript.html

### Categoria
Talk

**Comment by juceliohv** [comment]
### JHIPSTER
Alguém poderia falar sobre JHIPSTER? Explicar o que é, como funciona e se é uma boa escolha para desenvolvimento?

### Links
https://jhipster.github.io/

### Categoria
Tema

**Comment by YosephCode** [comment]
###REACT
Porque está crescendo no mercado e nas comunidades Front End tem se falado com frequência? 
O que diferencia dos outros frameworks? Qual a proposta do React?

###Links
https://github.com/facebook/react

###Categoria
Tema

**Comment by YosephCode** [comment]
### REACT
Porque está crescendo no mercado e nas comunidades Front End tem se falado com frequência? 
O que diferencia dos outros frameworks? Qual a proposta do React?

### Links
https://github.com/facebook/react

### Categoria
Tema

**Comment by diegoarcega** [comment]
## React-Native
Completando a sugestão acima, poderia também comentar sobre React-Native. 

## Links
https://medium.com/the-many/code-sharing-between-react-native-and-react-web-apps-b1e1de22fc53#.gpku18rv8

## Categoria
Tema
